on: push
name: Render manuscript

jobs:
  render:
    name: Render manusript
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: Render mansucript
        run: |-
          Rscript -e "lapply(fs::dir_ls("manuscript", glob="*.Rmd", recurse=TRUE), reprex::reprex_render)"      - name: Render README
